# Generated by Django 5.0.1 on 2024-02-03 11:29

import django.db.models.deletion
import shortuuid.django_fields
import userauths.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='other', max_length=20)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123', length=7, max_length=25, prefix='')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=userauths.models.user_directory_path)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='other', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_type', models.CharField(blank=True, choices=[('national identification number', 'national identification number'), ('Driving License', 'Driving License'), ('International Passport', 'International Passport')], max_length=200, null=True)),
                ('identity_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=userauths.models.user_directory_path)),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('verified', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
