# Generated by Django 5.0.1 on 2024-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
