# Generated by Django 5.0.1 on 2024-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_tags_hotel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
