# Generated by Django 5.0.1 on 2024-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotelcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcartitem',
            name='imagecart',
            field=models.ImageField(default='default_image.jpg', upload_to='your_upload_path'),
        ),
    ]
