# Generated by Django 5.0.1 on 2024-02-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotelcartitem_imagecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
