# Generated by Django 5.0.1 on 2024-02-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_hotelcartitem_imagecart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='befor_discount',
            new_name='before_discount',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sucess_id',
            new_name='success_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date_tracker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
